# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s66lQ78oUPE75Me7mmYT9uk9bVSEhPCT
"""

# ---------- If running in Colab ----------
# !pip install -q gradio

import gradio as gr
import random
import re

# ---------- Helpers ----------
def extract_number(text):
    m = re.search(r"(\d+(\.\d+)?)", str(text).replace(",", ""))
    return float(m.group(1)) if m else None

def format_inr(x):
    return f"₹{int(x):,}" if abs(x - int(x)) < 0.01 else f"₹{x:,.2f}"

def monthly_tax(income):
    annual = income * 12
    tax = 0
    if annual <= 250000:
        tax = 0
    elif annual <= 500000:
        tax = (annual - 250000) * 0.05
    elif annual <= 1000000:
        tax = 250000*0.05 + (annual - 500000)*0.2
    else:
        tax = 250000*0.05 + 500000*0.2 + (annual - 1000000)*0.3
    return round(tax/12,2)

def compound_amount(P, rate, years):
    A = P * ((1 + rate) ** years)
    return round(A,2)

# ---------- Main Bot ----------
def simple_finance_bot(user_msg, chat_history=None, state=None):
    if chat_history is None:
        chat_history = []
    if state is None:
        state = {"step":0, "mode":None, "idea":None, "budget":None, "deposit":None,
                 "years":None, "senior":None, "salary":None, "spending":None}

    text = user_msg.strip().lower()
    def add(msg):
        chat_history.append(msg)

    # Step 0: Greeting
    if state["step"] == 0:
        add(("bot", "✨ Hi there! What would you like to do today?\nOptions: Business, Interest, Profit-Loss"))
        state["step"] = 1
        return chat_history, state, ""

    # Step 1: Choose mode
    if state["step"] == 1:
        if "business" in text:
            state["mode"] = "business"
            state["step"] = 2
            add(("bot", "Great! Enter your business idea."))
        elif "interest" in text:
            state["mode"] = "interest"
            state["step"] = 10
            add(("bot", "Interest mode selected. Enter deposit amount:"))
        elif "profit" in text or "loss" in text:
            state["mode"] = "profit"
            state["step"] = 20
            add(("bot", "Profit/Loss mode. Enter your monthly income:"))
        else:
            add(("bot", "Please type one: Business, Interest, Profit-Loss."))
        return chat_history, state, ""

    # ---------- Business ----------
    if state["mode"] == "business":
        if state["step"] == 2:  # idea
            state["idea"] = user_msg
            state["step"] = 3
            add(("bot", f"Got it! Now enter your planned budget in numbers for {state['idea']}:"))
            return chat_history, state, ""
        if state["step"] == 3:  # budget
            amt = extract_number(user_msg)
            if amt:
                state["budget"] = amt
                add(("bot", f"Awesome! Your business '{state['idea']}' with budget {format_inr(amt)} is ready to start. Simple advice: Keep your expenses lean and start small!"))
                state["step"] = 99
            else:
                add(("bot", "Please enter a valid number for budget."))
            return chat_history, state, ""

    # ---------- Interest ----------
    if state["mode"] == "interest":
        if state["step"] == 10:
            amt = extract_number(user_msg)
            if amt:
                state["deposit"] = amt
                state["step"] = 11
                add(("bot", "Enter tenure in years (e.g., 2 or 3.5):"))
            else:
                add(("bot", "Enter a valid deposit amount in numbers."))
            return chat_history, state, ""
        if state["step"] == 11:
            yrs = extract_number(user_msg)
            if yrs:
                state["years"] = yrs
                state["step"] = 12
                add(("bot", "Are you a senior citizen? (yes/no)"))
            else:
                add(("bot", "Enter a valid number for years."))
            return chat_history, state, ""
        if state["step"] == 12:
            state["senior"] = True if "yes" in text else False
            rate = 0.08 if state["senior"] else 0.06
            A = compound_amount(state["deposit"], rate, state["years"])
            monthly = round(A/(state["years"]*12),2)
            add(("bot", f"Deposit: {format_inr(state['deposit'])}\nYears: {state['years']}\nRate: {rate*100:.1f}%\nTotal after {state['years']} years: {format_inr(A)}\nMonthly average: {format_inr(monthly)}"))
            state["step"] = 99
            return chat_history, state, ""

    # ---------- Profit-Loss ----------
    if state["mode"] == "profit":
        if state["step"] == 20:
            salary = extract_number(user_msg)
            if salary:
                state["salary"] = salary
                state["step"] = 21
                add(("bot", "Enter your monthly spending:"))
            else:
                add(("bot", "Enter valid salary in numbers."))
            return chat_history, state, ""
        if state["step"] == 21:
            spend = extract_number(user_msg)
            if spend:
                state["spending"] = spend
                profit = state["salary"] - spend
                tax = monthly_tax(state["salary"])
                net = profit - tax
                add(("bot", f"Monthly Income: {format_inr(state['salary'])}\nSpending: {format_inr(spend)}\nProfit before tax: {format_inr(profit)}\nCorporate Tax: {format_inr(tax)}\nNet Profit: {format_inr(net)}"))
                state["step"] = 99
            else:
                add(("bot", "Enter valid spending amount."))
            return chat_history, state, ""

    # ---------- Reset / Done ----------
    if state["step"] == 99:
        add(("bot", "Done ✅. Type 'reset' to start over or choose another mode."))
        if "reset" in text:
            state = {"step":0,"mode":None,"idea":None,"budget":None,"deposit":None,"years":None,"senior":None,"salary":None,"spending":None}
        return chat_history, state, ""

    add(("bot", "I didn't understand. Type 'Business', 'Interest', or 'Profit-Loss'."))
    return chat_history, state, ""

# ---------- Gradio UI ----------
with gr.Blocks() as demo:
    gr.Markdown("## 💰 Simple Finance Chatbot")
    chatbot = gr.Chatbot()
    msg = gr.Textbox(label="Type your message here...")
    state = gr.State({"step":0,"mode":None,"idea":None,"budget":None,"deposit":None,"years":None,"senior":None,"salary":None,"spending":None})

    msg.submit(simple_finance_bot, [msg, chatbot, state], [chatbot, state, msg])

    gr.Button("Reset Chat").click(lambda: ([], {"step":0,"mode":None,"idea":None,"budget":None,"deposit":None,"years":None,"senior":None,"salary":None,"spending":None},""), [], [chatbot, state, msg])

demo.launch()